name: Scrape Ollama Models

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
  
  push:
    branches:
      - main
    paths:
      - 'ollama_scraper.py'
      - '.github/workflows/scrape.yml'

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python ollama_scraper.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Ollama models data"
          file_pattern: out/ollama_models.json
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
